#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jul  7 17:04:36 2020

@author: alvarogonzalez
"""


from pymongo import MongoClient
import datetime
from unicodedata import normalize
import re

import urllib.parse
username = urllib.parse.quote_plus('aleja_user')
password = urllib.parse.quote_plus('02-10-91aldigovE')
mongo_client = MongoClient('mongodb://%s:%s@3.137.57.40' % (username, password))
db = mongo_client.aleja_bd


import gspread
import os
from oauth2client.service_account import ServiceAccountCredentials

current_file_dir = os.path.dirname(__file__)
other_file_path = os.path.join(current_file_dir, 'integracion aleja-a7c070957142.json')
scope = ['https://spreadsheets.google.com/feeds',
         'https://www.googleapis.com/auth/drive']
creds = ServiceAccountCredentials.from_json_keyfile_name(other_file_path,scope)
client = gspread.authorize(creds)
sheet = client.open('ciudades').sheet1

lista = sheet.get_all_records()
row = 0
ciudades = []
ciudades2 = []
stopers = ["la palma","el paso","seúl","contratacion","colombia","silvia","garzon","fundacion","la pe a","el banco","since","gonzalez","la mesa","murillo","la estrella","el rosario","paez"]
db.ciudades.remove()
for o in lista:
    
    c = o["ciudad"].capitalize()
    p = o["pais"].capitalize()
    
    if "?" in o["ciudad"]:
        c = c.replace("?","ñ")
    if c+"__"+p not in ciudades:
        db.ciudades.insert_one({"id":row,"ciudad":c,"pais":p})
        ciudades.append(c+"__"+p)
        if c.lower() not in stopers:
            ciudades2.append(c)
    else:
        print("repetido",c+"__"+p)
    row = row + 1


c = db.vacantes.find()
from fuzzywuzzy import fuzz

for o in c:
    s = o["obs"]
    s = re.sub(r"([^n\u0300-\u036f]|n(?!\u0303(?![\u0300-\u036f])))[\u0300-\u036f]+", r"\1", normalize( "NFD", s), 0, re.I)
    s = normalize( 'NFC', s)
    s = s.replace(".","punto")
    s = s.replace(",","coma")
    s = s.replace("@","arroba")
    s = s.replace("-","guion")
    sel = "Bogotá"
    for d in ciudades2:
        tsr = fuzz.token_set_ratio(d.lower(),s.lower())
        if tsr == 100:
            sel = d
            print(sel,o["id"],o["obs"][0:40])
            
            break
    db.vacantes.update_one({"id":o["id"]},{"$set":{"ciudad":sel}})
    